---
.gitignore:
  required:
    - 'appveyor.yml'
    - '.travis.yml'
    - 'update_report.txt'
Rakefile:
  requires:
    - puppetlabs_spec_helper/rake_tasks
    - puppet-lint/tasks/puppet-lint
    - puppet-syntax/tasks/puppet-syntax
    - metadata-json-lint/rake_task
    - rspec_junit_formatter
    - puppet_pot_generator/rake_tasks
  default_disabled_lint_checks:
    - disable_variable_scope
    - documentation
    - disable_puppet_url_without_modules
appveyor.yml:
  delete: true

