---
appveyor.yml:
  delete: true
.gitignore:
  required:
    - 'appveyor.yml'
    - '.travis.yml'
Rakefile:
  requires:
    - puppet-lint/tasks/puppet-lint
    - puppetlabs_spec_helper/rake_tasks
    - metadata-json-lint/rake_task
    - rspec_junit_formatter
    - puppet_pot_generator/rake_tasks
  extras:
    - PuppetLint.configuration.send('disable_variable_scope')
    - PuppetLint.configuration.send('documentation')
    - PuppetLint.configuration.send('disable_puppet_url_without_modules')
